import Head from 'next/head'
import Nav from "../components/Nav"
import Header from "../components/Header"
import request from '../utils/request';
import Result from "../components/Results"
export default function Home({results}) {
  console.log(results)
  return (
    <div className="">
      <Head>
        <title>Hulu 3.0 App</title>
        <meta name="description" content="Generated by create by shuhaib zahir" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
     <Header />
     <Nav />
    <Result results={results} />
    
    </div>
  )
}

 
export async function getServerSideProps(context){

  const genre = context.query.genre;
 

  const requests  = await fetch(`https://api.themoviedb.org/3${request[genre]?.url || request.fetchTrending.url}`).then(res=>res.json())

  return {
    props:{
      results:requests.results
    }
  }

}
